
name: spin_drama_earned
description: Spin Drama Earning App
publish_to: 'none'
environment:
  sdk: '>=3.0.0 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.2.2
flutter:
  uses-material-design: true
